### ISSUE TITLE
Feature Request - Please add an option to show/hide seconds for the clock time

### ISSUE THREAD

**Issue by mmarj** [hasinhayder/cronos#2]
Hey there!

I have a suggestion - how about adding an option to show/hide seconds for the clocks? It would be great to have the Main clock without the seconds, as it would provide a smoother 12-hour format view without line breaks.

As seen here:

<img width="1413" alt="Clock view with seconds" src="https://github.com/user-attachments/assets/97834e12-c520-458d-96d8-482cda4faf5e">

Thank you for your AMAZING work, @hasinhayder Bhaiya!! 😎 🆒 🤘

**Comment by hasinhayder** [comment]
It is already there - see the first option
<img width="435" alt="image" src="https://github.com/user-attachments/assets/57240b1c-bb0e-4f61-a5be-8c9f61e2ad60">

**Comment by mmarj** [comment]
Oops! I missed that! Cool.
